[server]
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#FFFFFF"
textColor="#E0E0E0"
backgroundColor="#000000"
secondaryBackgroundColor="#0A0A0A"
